---
title: "Chapter 1 figures"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(dplyr)
library(ggplot2)
theme_set(theme_bw())

both_scale <- scale_color_viridis_d(option = "cividis", begin = .1, end = .8, direction = -1)
both_fscale <- scale_fill_viridis_d(option = "cividis", begin = .1, end = .8, direction = -1)

```

```{r chapter specific setup}

all_sims <- read.csv(here::here("snre_talk", "media", "figures", "data", "ch2", "all_sims.csv"), stringsAsFactors = F)
demo_gmms <- read.csv(here::here("snre_talk", "media", "figures", "data", "ch2", "demo_gmms.csv"), stringsAsFactors = F)
winning_fits <- read.csv(here::here("snre_talk", "media", "figures", "data", "ch2", "winning_fits.csv"), stringsAsFactors = F)
all_preds_b <- read.csv(here::here("snre_talk", "media", "figures", "data", "ch2", "all_preds_b.csv"), stringsAsFactors = F)
all_preds_e <- read.csv(here::here("snre_talk", "media", "figures", "data", "ch2", "all_preds_e.csv"), stringsAsFactors = F)
```


```{r illustration of possible temporal trends in one currency}

rn <- "bbs_rtrg_28_4"

real_biomass <- filter(all_sims, matssname == rn, source == "sim") %>%
  mutate(time_direction = "Decreasing") 

backward_biomass <- real_biomass %>%
  mutate(timeperiod = rev(timeperiod),
         time_direction = "Increasing")

set.seed(1991)
random_biomass <- real_biomass %>%
  mutate(timeperiod = sample(timeperiod),
         time_direction = "No directional trend")

demo_dynamics <- bind_rows(real_biomass, backward_biomass, random_biomass)


demo_dynamics_plot <- ggplot(demo_dynamics, aes(timeperiod, abundance)) + 
  geom_line() + 
  facet_wrap(vars(time_direction)) + 
  geom_smooth(method = "lm", se = T, color = "black", linetype= 2, alpha = .15, size = .5) +
  xlab("Year") +
  ylab("Number of individuals") 

demo_dynamics_plot

ggsave(here::here("snre_talk", "media", "figures", "figs", "ch2", "demo_dynamics_plot.jpeg"), plot = demo_dynamics_plot, device = "jpeg", width = 5.5, height = 3, units = c("in"), dpi = 600)


```

```{r example of decoupling}

real_decoupled <- filter(all_sims, matssname == rn) %>%
    mutate(Currency = ifelse(source == "sim", "Individuals driven", "Biomass driven")) 

decoupled_plot <- ggplot(real_decoupled, aes(timeperiod, total_biomass, color = Currency)) +
  geom_point() +
  geom_line() +
  geom_smooth(method = "glm", method.args = c(family = "Gamma"), se = F, linetype = 2, size = .5) +
  both_scale +
  theme(legend.position = "bottom") +
  xlab("Year") +
  ylab("Expected biomass")

decoupled_plot

ggsave(here::here("snre_talk", "media", "figures", "figs", "ch2", "demo_decouple_plot.jpeg"), plot = decoupled_plot, device = "jpeg", width = 5.5, height = 3, units = c("in"), dpi = 600)

```

```{r example of size shifts}

demo_gmms <- demo_gmms %>%
    mutate(Currency = ifelse(Dynamics == "Abundance driven", "Individuals driven", "Biomass driven"),
           `Time` = time)

isd_plots <- ggplot(filter(demo_gmms, exp(mass) > 5, exp(mass) < 5000, Dynamics == "Observed"), aes(exp(mass), density, linetype = Time)) + 
  geom_line() + 
  theme(legend.position = "bottom") + 
  ylab("Probability density")+ 
  xlab("Mass (g); note log scale") +
  scale_x_log10()
isd_plots

ggsave(here::here("snre_talk", "media", "figures", "figs", "ch2", "demo_size_shift.jpeg"), plot = isd_plots, device = "jpeg", width = 5, height = 3, units = c("in"), dpi = 600)


```

```{r example of multimodal ISD}
one_isd <- ggplot(filter(demo_gmms, exp(mass) > 5, exp(mass) < 5000, Dynamics == "Observed", Time == "begin"), aes(exp(mass), density)) + 
  geom_line() + 
  ylab("Probability density")+ 
  xlab("Mass (g); note log scale") +
  scale_x_log10()
one_isd


ggsave(here::here("snre_talk", "media", "figures", "figs", "ch2", "one_isd.jpeg"), plot = one_isd, device = "jpeg", width = 5, height = 3, units = c("in"), dpi = 600)

```


```{r example of possible couple decouple trends}



real_coupled <- filter(all_sims, matssname == "bbs_rtrg_82_60") %>%
    mutate(Currency = ifelse(source == "sim", "Individuals driven", "Biomass driven"),
           Outcome = "Coupled trends")

real_notrend <- filter(all_sims, matssname == "bbs_rtrg_50_27") %>%
    mutate(Currency = ifelse(source == "sim", "Individuals driven", "Biomass driven"),
           Outcome = "No directional trends")

real_examples <- real_decoupled %>%
  mutate(Outcome = "Decoupled trends") %>%
  bind_rows(real_coupled) %>%
  bind_rows(real_notrend)


example_plot <- ggplot(real_examples, aes(timeperiod, total_biomass, color = Currency)) +
  geom_point() +
  geom_line() +
  geom_smooth(method = "glm", method.args = c(family = "Gamma"), se = F, linetype = 2, size = .5) +
  facet_wrap(vars(Outcome), scales = "free") +
  both_scale +
  theme(legend.position = "bottom") +
  xlab("Year") +
  ylab("Expected biomass")
example_plot

ggsave(here::here("snre_talk", "media", "figures", "figs", "ch2", "demo_outcomes.jpeg"), plot = example_plot, device = "jpeg", width =8, height = 3.5, units = c("in"), dpi = 600)


```


```{r abundance and biomass change}

trend_fits <- filter(winning_fits, modelcomplexity > 1) %>%
  select(matssname, ratio_sim, ratio_real) %>%
  tidyr::pivot_longer(-matssname, names_to = "sim", values_to = "Change") %>%
  mutate(Currency = ifelse(sim == "ratio_sim", "Individuals driven", "Biomass driven"))

trend_texts <- data.frame(
  lat = c(.2, 3),
  long = 60,
  labs = c("67% decreases", "33% increases"),
  Currency = "Individuals driven"
)

abundance_change <- ggplot(trend_fits, aes(Change, color = Currency, fill = Currency)) +
  geom_point(aes(y = 0), alpha = 0) +
  geom_histogram(data = filter(trend_fits, Currency == "Individuals driven"), boundary = 1) +
  geom_vline(xintercept = 1) +
  geom_text(data = trend_texts, aes(lat, long, label = labs)) +
  scale_x_log10() +
  xlab("Change over time\n(last fitted value/first fitted value; note log scale)") +
  ylab("Number of communities") +
  ggtitle("Individuals-driven change") +
  both_scale + 
  both_fscale +
  theme(legend.position = "none")
abundance_change
ggsave(here::here("snre_talk", "media", "figures", "figs", "ch2", "abundance_change.jpeg"), plot = abundance_change, device = "jpeg", width =4, height = 3.5, units = c("in"), dpi = 600)


biomass_trend_texts <- data.frame(
  lat = c(.2, 3),
  long = 60,
  labs = c("51% decreases", "49% increases"),
  Currency = "Biomass driven"
)

biomass_change <- ggplot(trend_fits, aes(Change, color = Currency, fill = Currency)) +
  geom_point(aes(y = 0), alpha = 0) +
  geom_histogram(data = filter(trend_fits, Currency == "Biomass driven"), boundary = 1) +
  geom_vline(xintercept = 1) +
  geom_text(data = biomass_trend_texts, aes(lat, long, label = labs)) +
  scale_x_log10() +
  xlab("Change over time\n(last fitted value/first fitted value; note log scale)") +
  ylab("Number of communities") +
  ggtitle("Biomass-driven change") +
  both_scale + 
  both_fscale +
  theme(legend.position = "none")
biomass_change
ggsave(here::here("snre_talk", "media", "figures", "figs", "ch2", "biomass_change.jpeg"), plot = biomass_change, device = "jpeg", width =4, height = 3.5, units = c("in"), dpi = 600)

```

```{r decoupling results}

interaction_all_fits <- all_preds_b %>% 
  # get just the change ratios from the interaction models - regardless of whether the interaction model is the best-fitting model. this is because we want an estimate of the slope, we'll color by model fit in a minute
  group_by_all() %>% 
  filter(grepl( "* source",model_formula), model_family == "Gamma") %>%
  mutate(plus = substr(model_formula, 12,12) == "+") %>% filter(!plus) %>%
  ungroup() %>%
  # now join to *winning* formulas to get the best fitting formula
  left_join(select(winning_fits, matssname, model_formula, modelcomplexity) %>%
              rename(winning_formula = model_formula)) %>%
  select(winning_formula, ratio_sim, ratio_real, matssname, modelcomplexity) %>%
  mutate(currency = "Biomass")



all_interaction <- bind_rows(interaction_all_fits) %>%
  mutate(`Best fitting model` = ifelse(modelcomplexity == 1, "No trend", ifelse(modelcomplexity == 2, "Coupled trend", "Decoupled trends")))


decoupling_plot <- ggplot(all_interaction, aes(ratio_sim, ratio_real, color = `Best fitting model`)) + 
  geom_point(alpha = .5) + 
  scale_y_log10() + 
  scale_x_log10() + 
  scale_color_viridis_d(option = "mako", end = .8, direction = -1) + 
  theme(legend.position = "bottom") + 
  geom_abline(intercept = 0, slope = 1) + 
 geom_vline(xintercept = 1, linetype = 2) + 
  geom_hline(yintercept = 1, linetype =2) +
  xlab("Individuals-driven change \n Ratio of last fitted value to first fitted value") + 
  ylab("Biomass-driven change \n Ratio of last fitted value to first fitted value") 

decoupling_plot

ggsave(here::here("snre_talk", "media", "figures", "figs", "ch2", "decoupled_slopes.jpeg"), plot = decoupling_plot, device = "jpeg", width =4, height = 3.5, units = c("in"), dpi = 600)

```

```{r mean mass}

winning_fits <- winning_fits %>%
  rename(`Best fitting model` = Best.fitting.model)
isd_mean_change_plot <-  ggplot(winning_fits, aes(log_ratio, color = `Best fitting model`, fill= `Best fitting model`)) + 
  geom_histogram() + 
  facet_wrap(vars(`Best fitting model`), scales = 'free_y', ncol = 3) +
  scale_color_viridis_d(option = "mako", end = .8, direction = -1) +     
  scale_fill_viridis_d(option = "mako", end = .8, direction = -1) +
  theme(legend.position = "none") +
  xlab("Mean mass log ratio") +
  ylab("Count") +
  ggtitle("Mean size change")
isd_mean_change_plot

ggsave(here::here("snre_talk", "media", "figures", "figs", "ch2", "mean_size_change.jpeg"), plot = isd_mean_change_plot, device = "jpeg", width =7, height = 3.5, units = c("in"), dpi = 600)

```
