---
title: "Chapter 3 figures"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(dplyr)
library(ggplot2)
theme_set(theme_bw())

both_scale <- scale_color_viridis_d(option = "cividis", begin = .1, end = .8, direction = -1)
both_fscale <- scale_fill_viridis_d(option = "cividis", begin = .1, end = .8, direction = -1)

```

```{r chapter specific setup}

library(scadsanalysis)
library(multipanelfigure)

all_di <- read.csv(here::here("snre_talk", "media", "figures", "data", "ch3", "all_di.csv"))

```

```{r some demo sads, fig.dim = c(6,3)}

bbs_spab <- scadsanalysis::load_dataset("bbs", here::here("snre_talk", "media", "figures", "data", "ch3"))

mouse_spab <- portalr::abundance(time = "date", level = "treatment") 
  

plant_spab <- scadsanalysis::load_dataset("portal_plants", here::here("snre_talk", "media", "figures", "data", "ch3"))

a_bird_sad <- bbs_spab %>%
  filter(site == 25009) %>%
  mutate(taxon = "Birds")
a_mammal_sad <- mouse_spab %>%
  mutate(year = as.integer(format.Date(censusdate, "%Y"))) %>%
  filter(treatment == "control",
         year %in% 1994:1999) %>%
  select(-treatment, -year, -censusdate) %>%
  mutate(id_col = dplyr::row_number()) %>%
  tidyr::pivot_longer(-id_col, names_to = "sp", values_to = "abund") %>%
  group_by(sp) %>%
  summarize(abund = sum(abund)) %>%
  ungroup() %>%
  arrange(abund) %>%
  mutate(rank = row_number()) %>%
  mutate(taxon = "Desert rodents")
a_plant_sad <- plant_spab %>%
  filter(site == "1994_summer") %>%
  mutate(taxon = "Desert annual plants")

long_example_sads <- bind_rows(a_bird_sad, a_mammal_sad, a_plant_sad)


# birds <- ggplot(a_bird_sad, aes(rank, abund)) +
#   geom_line() + 
#   ggtitle("Breeding birds") +
#   xlab("Rank") +
#   ylab("Abundance")
# mice <- ggplot(a_mammal_sad, aes(rank, abund)) + 
#   geom_line()+ 
#   ggtitle("Desert rodents") +
#   xlab("Rank") +
#   ylab("Abundance")
# plants <- ggplot(a_plant_sad, aes(rank, abund)) +
#   geom_line()+ 
#   ggtitle("Desert annuals") +
#   xlab("Rank") +
#   ylab("Abundance")

example_sads_plot <- ggplot(long_example_sads, aes(rank, abund)) +
  geom_line() +
  facet_wrap(vars(taxon), ncol = 3, scales = "free") +
  xlab("Rank") +
  ylab("Abundance")
example_sads_plot
ggsave(here::here("snre_talk", "media", "figures", "figs", "ch3", "example_sads_plot.jpg"), plot = example_sads_plot, device = "jpeg", width = 5, height = 2.5, units = "in", dpi = 600)

```
```{r feasible set}

#mamm_p <- readRDS(here::here("snre_talk", "media", "figures", "data", "ch3", "masterp_mamm.Rds"))
# 
# a_mammal_fs <- feasiblesads::sample_fs(s = nrow(a_mammal_sad), n = sum(a_mammal_sad$abund), nsamples = 4000, p_table = mamm_p)
# 
# write.csv(a_mammal_fs, here::here("snre_talk", "media", "figures", "data", "ch3", "mammal_fs_draws.csv"), row.names = F)

a_mammal_fs <- read.csv(here::here("snre_talk", "media", "figures", "data", "ch3", "mammal_fs_draws.csv"), stringsAsFactors = F)

mammal_fs_draws <- a_mammal_fs %>% 
  as.data.frame() %>%
  mutate(sim = row_number()) %>%
  tidyr::pivot_longer(-sim, names_to = "sp", values_to = "abund") %>%
  group_by(sim) %>%
  arrange(abund) %>%
  mutate(rank = row_number(),
         Evenness = vegan::diversity(abund, index = "simpson"),
         `SAD type` = "Mathematically generated") %>%
  ungroup()

a_mammal_sad <- a_mammal_sad %>%
  mutate(sim = -99, Evenness = vegan::diversity(abund, index = "simpson"),
         `SAD type` = "Real")

all_mammal_sads <- bind_rows(mammal_fs_draws, a_mammal_sad)

feasible_set_draws_plot <- ggplot(all_mammal_sads, aes(rank, abund, group = sim, color = Evenness, linetype = `SAD type`)) + 
  geom_line(alpha = 0) +
  geom_line(data = filter(all_mammal_sads, `SAD type` != "Real")) + 
#    geom_line(data = filter(all_mammal_sads, `SAD type` == "Real")) + 

  scale_color_viridis_c(option = "mako") +
  theme(legend.position = "right", legend.direction = "vertical") +
#  ggtitle("Mathematically-generated SADs") +
  xlab("Rank") +
  ylab("Abundance")
ggsave(here::here("snre_talk", "media", "figures", "figs", "ch3", "feasible_set_draws_plot.jpeg"), plot = feasible_set_draws_plot, device = "jpeg", width = 7, height = 4, units = "in", dpi = 600)


```


```{r feasible set with deviation}


feasible_set_draws_plot_with_real <- ggplot(all_mammal_sads, aes(rank, abund, group = sim, color = Evenness, linetype = `SAD type`)) + 
  geom_line(alpha = 0) +
  geom_line(data = filter(all_mammal_sads, `SAD type` != "Real")) + 
    geom_line(data = filter(all_mammal_sads, `SAD type` == "Real")) + 

  scale_color_viridis_c(option = "mako") +
  theme(legend.position = "right", legend.direction = "vertical") +
#  ggtitle("Mathematically-generated SADs") +
  xlab("Rank") +
  ylab("Abundance")

ggsave(here::here("snre_talk", "media", "figures", "figs", "ch3", "feasible_set_draws_plot_real.jpeg"), plot = feasible_set_draws_plot_with_real, device = "jpeg", width = 7, height = 4, units = "in", dpi = 600)

```

```{r evenness hists}

evenness_hist <- ggplot(mammal_fs_draws, aes(Evenness)) + 
  geom_histogram() +
  geom_vline(xintercept = a_mammal_sad$Evenness, color = "red") +
  ylab("Number of SADs") +
  xlab("Simpson's evenness")

evenness_hist

ggsave(here::here("snre_talk", "media", "figures", "figs", "ch3", "even_hist_example.jpeg"), plot = evenness_hist, device = "jpeg", width = 4, height = 4, units = "in", dpi = 600)


```

```{r evenness percentile calc}
even_scores <- mammal_fs_draws %>%
  select(sim, Evenness) %>%
  distinct()

real_even_score <- a_mammal_sad$Evenness %>% unique()

mean(even_scores >= real_even_score)

```


```{r s x n plot}

```


```{r overall deviations evenness}

all_di <- all_di %>%
  mutate(log_nparts = log(gmp:::as.double.bigz(nparts)),
         log_nsamples = log(nsamples),
         log_s0 = log(s0),
         log_n0 = log(n0)) %>%
  filter(n0 != s0,
         s0 != 1,
         !singletons,
         n0 != (s0 + 1)) %>%
  mutate(dat = ifelse(grepl(dat, pattern = "fia"), "fia", dat),
         dat = ifelse(dat == "misc_abund_short", "misc_abund", dat)) %>%
  mutate(Dataset = dat,
         Dataset = ifelse(Dataset == "fia", "FIA (Trees)", Dataset),
         Dataset = ifelse(Dataset == "bbs", "Breeding Bird Survey", Dataset),
         Dataset = ifelse(Dataset == "mcdb", "Mammal Communities", Dataset),
         Dataset = ifelse(Dataset == "gentry", "Gentry (Trees)", Dataset),
         Dataset = ifelse(Dataset == "misc_abund", "Misc. Abundance", Dataset)) %>%
  filter(nparts > 20) %>%
  mutate(Dataset_short = ifelse(Dataset == "FIA", "FIA", 
                                ifelse(Dataset == "Breeding Bird Survey", "BBS", 
                                       ifelse(Dataset == "Mammal Communities", "Mammals", ifelse(Dataset == "Gentry", "Gentry", "Misc.")))))

all_di <- all_di %>%
  group_by_all() %>%
  mutate(skew_percentile_mean = mean(skew_percentile, skew_percentile_excl),
         simpson_percentile_mean = mean(simpson_percentile,simpson_percentile_excl),
         shannon_percentile_mean = mean(shannon_percentile, shannon_percentile_excl),
         nsingletons_percentile_mean = mean(nsingletons_percentile, nsingletons_percentile_excl),) %>%
  ungroup()


plot_percentile_hist <- function(di_df, col_name, plot_name, tails = 2, facetvar = "Dataset", min_s0 = 0) {
  if(tails == 2) {
    cutoff_percentiles = c(2.5, 97.5)
    min_nparts = 40
  } else if (tails== 1) {
    cutoff_percentiles = c(95)
    min_nparts = 20
  }

  di_df <- di_df %>%
    mutate(response = (di_df[[col_name]]),
           facetvar = di_df[[facetvar]])

  ggplot(filter(di_df, nparts > min_nparts, s0 >= min_s0), aes(response)) +
    geom_histogram(bins = 40, boundary = 100) +
    geom_vline(xintercept = cutoff_percentiles, color = "red") +
    ggtitle(plot_name) +
    facet_wrap(vars(facetvar), ncol = 2, scales = "free_y")+
    scale_y_continuous(n.breaks = 3)

}

evenness_results <- plot_percentile_hist(all_di, "simpson_percentile_mean", "Simpson evenness", facetvar = "Dataset") + 
  xlab("Percentile score") +
  ylab("Number of communities")

evenness_results


ggsave(here::here("snre_talk", "media", "figures", "figs", "ch3", "even_results.jpeg"), plot = evenness_results, device = "jpeg", width = 5, height = 3, units = "in", dpi = 600)
```

```{r gentry deviations}

just_gentry_results <- plot_percentile_hist(filter(all_di, dat == "gentry"), "simpson_percentile_mean", "Simpson evenness", facetvar = "Dataset") + 
  xlab("Percentile score") +
  ylab("Number of communities")

just_gentry_results

ggsave(here::here("snre_talk", "media", "figures", "figs", "ch3", "gentry_even_results.jpeg"), plot = just_gentry_results, device = "jpeg", width = 3, height = 2, units = "in", dpi = 600)
```

```{r fia deviations}


just_fia_results <- plot_percentile_hist(filter(all_di, dat %in% c("fia", "fia_short", "fia_small")), "simpson_percentile_mean", "Simpson evenness", facetvar = "Dataset") + 
  xlab("Percentile score") +
  ylab("Number of communities")

just_fia_results

ggsave(here::here("snre_talk", "media", "figures", "figs", "ch3", "fia_even_results.jpeg"), plot = just_fia_results, device = "jpeg", width = 3, height = 2, units = "in", dpi = 600)
```
