---
title: "Of rodents and randomness"
subtitle: "Macroecological approaches to community structure"
date: "February 28, 2022"
author: "Renata M. Diaz"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(dplyr)
library(ggplot2)
theme_set(theme_bw())
```


# Macroecology and community ecology

## 

A macroecological approach to **community ecology**

- How (and why) are _abundance_, _biomass_, and _resource use_ distributed among species in ecological communities?
- How (and why) does this change over time?
- How (and why) do species' dynamics combine to produce community-level phenomena?

## 

A **macroecological approach** to community ecology

- "Community ecology is a mess"...
- ...but may contain "fuzzy generalities"



## 

A macroecological approach to community ecology

- is grounded in **ecology**: 
    - natural history
    - experiments
    - classic concepts

## 

A macroecological approach to community ecology


- is grounded in **ecology**: 
    - natural history
    - experiments
    - classic concepts
- draws on **complex systems science**:
    - data-intensive synthesis
    - focus on emergent phenomena
    - methods and concepts transcend disciplines


## 

A macroecological approach to community ecology


- Focus on **community-level properties**
    - Total **abundance**, **biomass**, **energy use**
- **Distributions** among species and organisms 

<!-- here you will want to illustrate SADs and ISDs, at least. but also not sure if this slide even belongs here --> 



## Of rodents and randomness

**I. How do community-level properties respond to species loss?**

A long-term experimental perspective

**II. How do changes in community structure modulate long-term trends in biodiversity?**

A continental-scale synthesis

**III. What can ubiquitous mathematical constraints on complex systems reveal about "laws" in community ecology?**

A cross-disciplinary synthesis

## 

(logos/some acknowledgement of: research computing, bbs, portal, open data/open access; r....? IDK if this goes)

# I. Impacts of species loss on community function in a changing world

## 

(placeholder for google map of portal and a cute krat)


## Community function

Total **energy use** or **biomass**

## Species loss directly impacts function

(illustration of removal of kangaroo rats --> less etot)

## Compensation can offset declines in function due to species loss

(illustration of removal of kangaroo rats, but more pb --> the same etot)

## Compensation linked to functional redundancy

## Functional redundancy may change over time

Addition of new species from the **metacommunity**

Changes in the dynamics between the **species already present**

**Impacts of species loss on community function may therefore be temporally variable and context dependent**


## The Portal Project

Long-term experiment examining the consequences of species loss in a desert ecosystem

## The Portal Project

(cute krat pic)

Kangaroo rats are key players in this system

## The Portal Project

(pic of exclosure plot fencing? rodent census happening?)

**How do community properties respond to kangaroo rat removal?**

## The Portal Project

(pic of binders of data?)

Over 40 years of data and 500+ rodent censuses

**How do these responses change over time?**

## Community reorganization events

(figure of PB % community energy use, pic of PB?)

## Long-term environmental change

(figure of Dipo % community energy use)

##

**How have shifts in community composition and species interactions affected how community function responds to kangaroo rat removal?**

## 

(plot of energetic compensation)

**Compensatory dynamics linked to C. baileyi**

## 

(plot of energetic compensation, highlight 1996)

The 1996 transition is PB colonizing the site

##

(plot of energetic compensation, highlight 2010)

The 2010 transition is PB falling out of the site 

## 

(plot of energetic compensation, highlight 2010)

(inset plot of PB % abundance - still present)

**Decline in functional redundancy among the same set of species**

<!-- this next may be a detour that we don't have time for --> 

<!-- ##  -->

<!-- (plot of total energy use) -->

<!-- Total energy use remains higher since 2010 than pre-1996 -->

<!-- ##  -->

<!-- (plot of total energy use) -->

<!-- (inset % dipo energy use) -->

<!-- The altered net effect is due to a long-term shift in community composition -->

## 

**Compensation for species loss is context dependent**

Species that compensate under some conditions may not under others

As conditions change, new species may be required to maintain or restore community function 

This may be difficult or impossible in the Anthropocene

##

Link/tinyurl to:

- preprint/Ecology page
- Git repo

# II. Shifts in community structure modulate long-term trends in community-level properties

## Long-term trends in biodiversity

(collage of biodiversity trends papers titles? I hate those)

What are long term trends in biological diversity?

Specifically, community-level **abundance** and **function**?

## Currencies of community abundance

(illustration of total abundance vs total biomass, total bmr)

Size- and abundance- based currencies are linked, but not equivalent

## Decoupling between different currencies

(illustration of shifts in community structure decoupling)

Size shifts can decouple trends in abundance, biomass, and energy use

## Barriers to synthesis

Aquatic, tree systems: Plentiful data and statistically well-behaved size structures

(plot of tree ISD?)


## Barriers to synthesis

Terrestrial animal systems: Relatively little data and statistically complex size structures

(plot of bird ISD - Thibault or one of these)

## Recent advances 

Allometry --> estimates of size measurements

Statistical and null model approaches to work with complex ISDs and temporal dynamics

## Continental-scale synthesis

Breeding Bird Survey: Continental-scale citizen science beginning in 1963

High-performance computing for data-intensive synthesis

##

**What are the 30-year trends in abundance, biomass, and energy use for breeding bird communities in North America?**

**Do these currencies have similar or contrasting trends?**

**How do changes in community structure decouple long-term trends in community-level properties?**

## 

(illustration of possible long-term trends: increase, decrease, no trend that can be either flat or high var no trend)

##

(illustration of possible signatures of coupling/decoupling)

##

(illustration of possible signatures of coupling/decoupling)

(add illustration of how the size structure can contribute there - cartoon perhaps - very strong/simple size shift)

## 

(return to illustration of possible outcomes and add %/count breakdown)

For about 1/3 of routes, no temporal trend.

For the rest, a mixture of ~joint and decoupled trends.

## 

(plot of abundance-driven dynamics)

Changes in community-wide **abundance** are dominated by declines

## 

(add plot of biomass-driven dynamics)

However, changes in community-wide **biomass** are equally split among declines and increases

<!-- ## energy use might be a detour-->

<!-- (add plot of energy-driven dynamics?) -->

<!-- And changes in **energy use** are again more similar to abundance -->


##

(Visualizing decoupling plot)

When abundance and biomass don't change together, biomass typically declines less than abundance.

##

(Add mean mass plot)

So **increases** in mean body size are offsetting change in biomass expected given change in abundance.


##

**Contrasts** with general concerns about size-biased extinctions/defaunation in the Anthropocene

**Consistent** with trends observed for BBS

**Illustrates** that these currencies are nonequivalent

## 

link to github repo

## 

link to github repo

add link to BBSsize github repo and pkgdown site; talk about scientific software in support of re-use/re-deployment of size data methods

# III. Ecological communities as complex systems: the species abundance distribution as a case study

